#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

- name: Allow reflection and health to everyone
  action: allow
  condition: method.startsWith('/grpc.reflection.') || method.startsWith('/grpc.health.')

- name: Allow specific methods to client
  action: allow
  condition: |
    subject.name == 'system:serviceaccount:innabox:client' &&
    method in [
      '/events.v1/Watch',
      '/fulfillment.v1.ClusterTemplates/Get',
      '/fulfillment.v1.ClusterTemplates/List',
      '/fulfillment.v1.Clusters/Delete',
      '/fulfillment.v1.Clusters/Get',
      '/fulfillment.v1.Clusters/GetKubeconfig',
      '/fulfillment.v1.Clusters/GetKubeconfigViaHttp',
      '/fulfillment.v1.Clusters/List',
      '/fulfillment.v1.Clusters/Update',
      '/fulfillment.v1.HostClasses/Get',
      '/fulfillment.v1.HostClasses/List',
    ]

- name: Allow everything to admin and controller
  action: allow
  condition: |
    subject.name in [
      'system:serviceaccount:innabox:admin',
      'system:serviceaccount:innabox:controller',
      'system:serviceaccount:cloudkit-operator-system:cloudkit-operator-controller-manager',
    ]
